### ISSUE TITLE
python3.8

### ISSUE THREAD

**Issue by CoderXuans** [Slimercorp/MPC-Carla#1]
@Slimercorp 
Hi，I am using Ubuntu, and Python 3.8 should also work with CARLA, as I am able to run it.
I want to achieve the output of future trajectories using a large model and control it with MPC. The future trajectory part has already been obtained. Can this project be used to implement that?

**Comment by Slimercorp** [comment]
@CoderXuans 
Hi! Yes, you can definitely use this project to achieve your goal. Good luck with your work!

**Comment by CoderXuans** [comment]
Thanks！
