### ISSUE TITLE
Navigation Questions

### ISSUE THREAD

**Issue by CoderXuans** [Slimercorp/MPC-Carla#2]
@Slimercorp 
Hello,
1、Today I found that the local planning in carla/PythonAPI/carla/agents/navigation/local_planner.py uses the VehiclePIDController class, which implements a PID controller for local planning. If I want to implement an MPC controller during the evaluation of autonomous driving, do I also need to change the VehiclePIDController used in the navigation section of the CARLA package?
2、How is the navigation problem solved in your project?

**Comment by Slimercorp** [comment]
@CoderXuans
Hello,
1. Unfortunately, I'm not very familiar with the CARLA simulator, so I can't answer your question.
2. It's just a small pet project, and I wasn't trying to solve a navigation problem. I simply tried to make the ego vehicle follow my predefined trajectory (a figure-eight and a straight line).
